### PR TITLE
Supports to_tsquery and to_tsvector config parameter

### PR DESCRIPTION
**Pull request by davividal**
Address #19 .

### CODE REVIEW

**Comment by shandyDev** [comment]
Need change unit test for this.

**Comment by dmitrijivanenko** [comment]
First of all, thank You for contributing to our library. Regarding the tests issue, in order to solve the problem you have to add expectation of 

`$parser->getLexer()` and also mock the `$parser->getLexer()->isNextToken(Lexer::T_COMMA)`.

Also, it would be nice if you rewrite the test to cover your code

**Comment by davividal** [comment]
Hey @dmitrijivanenko , thank you for your feedback.
I'm looking into that right now.

What PHP versions are you aiming?
From travis I saw PHP 7.1 and 7.2, but on composer it is 5.4+.
I'm asking this because the test syntax is 5.5+ (`Parser::class` is available on PHP 5.5+).

**Comment by dmitrijivanenko** [comment]
Yeah, You are right our fault, we will fix it, but anyway, for test suite You can use anyof them.

**Comment by davividal** [comment]
@dmitrijivanenko done.

Any other issue?

**Pull request merged**
